version: "2"
services:
  mysql:
    image: mysql
    restart: always
    command: --authentication_policy=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:80"
    volumes:
      - ./phpmyadminConfig.php:/etc/phpmyadmin/config.user.inc.php
volumes:
  db_data:
